INSERT INTO "cards" ("id", "member_name", "group_name", "image_url", "rarity_class", "card_name", "series", "can_be_dropped", "hidden", "static_url", "created_for", "created_reason") VALUES
    (267, 'Bom', '2NE1', 'https://i.imgur.com/jafmj37.mp4', 'S', 'Bom', 'Series 3', 'true', 'false', 'https://i.imgur.com/htPa1sd.png', NULL, NULL),
    (268, 'Dara', '2NE1', 'https://i.imgur.com/4exxKzC.mp4', 'B', 'Dara', 'Series 3', 'true', 'false', 'https://i.imgur.com/bLNT9vm.png', NULL, NULL),
    (269, 'Minzy', '2NE1', 'https://i.imgur.com/VhvuGMG.mp4', 'C', 'Minzy', 'Series 3', 'true', 'false', 'https://i.imgur.com/kmZCO0k.png', NULL, NULL),
    (270, 'CL', '2NE1', 'https://i.imgur.com/THmcCyv.mp4', 'D', 'CL', 'Series 3', 'true', 'false', 'https://i.imgur.com/5eUUvwP.png', NULL, NULL),
    (271, 'Sohee', 'ALICE', 'https://i.imgur.com/CzGH291.mp4', 'SSS', 'Sohee', 'Series 3', 'true', 'false', 'https://i.imgur.com/lewJwyx.gif', NULL, NULL),
    (272, 'Karin', 'ALICE', 'https://i.imgur.com/VL8TQwr.mp4', 'A', 'Karin', 'Series 3', 'true', 'false', 'https://i.imgur.com/oza1qH6.png', NULL, NULL),
    (273, 'Do-A', 'ALICE', 'https://i.imgur.com/QJvX18t.mp4', 'B', 'Do-A', 'Series 3', 'true', 'false', 'https://i.imgur.com/ELqCvSY.png', NULL, NULL),
    (274, 'EJ', 'ALICE', 'https://i.imgur.com/uNPmlJl.mp4', 'C', 'EJ', 'Series 3', 'true', 'false', 'https://i.imgur.com/jsio5l8.png', NULL, NULL),
    (275, 'Yukyung', 'ALICE', 'https://i.imgur.com/Qqn854l.mp4', 'C', 'Yukyung', 'Series 3', 'true', 'false', 'https://i.imgur.com/tFjuQTI.png', NULL, NULL),
    (276, 'Chaejeong', 'ALICE', 'https://i.imgur.com/AAXXLYG.mp4', 'D', 'Chaejeong', 'Series 3', 'true', 'false', 'https://i.imgur.com/R3r45ee.png', NULL, NULL),
    (277, 'Yeonje', 'ALICE', 'https://i.imgur.com/7uyBTH6.mp4', 'D', 'Yeonje', 'Series 3', 'true', 'false', 'https://i.imgur.com/nDn05Hg.png', NULL, NULL),
    (278, 'Hayoung', 'Apink', 'https://i.imgur.com/DnaGP3J.mp4', 'SSS', 'Hayoung', 'Series 3', 'true', 'false', 'https://i.imgur.com/Uoj0TA9.gif', NULL, NULL),
    (279, 'Namjoo', 'Apink', 'https://i.imgur.com/Mr802HB.mp4', 'A', 'Namjoo', 'Series 3', 'true', 'false', 'https://i.imgur.com/1uvySYn.png', NULL, NULL),
    (280, 'Chorong', 'Apink', 'https://i.imgur.com/XRnzWPp.mp4', 'A', 'Chorong', 'Series 3', 'true', 'false', 'https://i.imgur.com/dqQnbzi.png', NULL, NULL),
    (281, 'Bomi', 'Apink', 'https://i.imgur.com/gKSekWY.mp4', 'B', 'Bomi', 'Series 3', 'true', 'false', 'https://i.imgur.com/D9hoO9I.png', NULL, NULL),
    (282, 'Eunji', 'Apink', 'https://i.imgur.com/zSnABgt.mp4', 'B', 'Eunji', 'Series 3', 'true', 'false', 'https://i.imgur.com/abLIAlb.png', NULL, NULL),
    (283, 'Seo A', 'Bambino', 'https://i.imgur.com/K19bzBj.mp4', 'S', 'Seo A', 'Series 3', 'true', 'false', 'https://i.imgur.com/YyTqXlk.png', NULL, NULL),
    (284, 'Dahee', 'Bambino', 'https://i.imgur.com/okU9wh6.mp4', 'C', 'Dahee', 'Series 3', 'true', 'false', 'https://i.imgur.com/Bbzxt8e.png', NULL, NULL),
    (285, 'Minhee', 'Bambino', 'https://i.imgur.com/OfIVngv.mp4', 'D', 'Minhee', 'Series 3', 'true', 'false', 'https://i.imgur.com/1LqyHxF.png', NULL, NULL),
    (286, 'Sheon', 'Billlie', 'https://i.imgur.com/VL2Z7DO.mp4', 'SSS', 'Sheon', 'Series 3', 'true', 'false', 'https://i.imgur.com/EA2QSW3.gif', NULL, NULL),
    (287, 'Haram', 'Billlie', 'https://i.imgur.com/afyM5UI.mp4', 'S', 'Haram', 'Series 3', 'true', 'false', 'https://i.imgur.com/pIMx4UZ.png', NULL, NULL),
    (288, 'Haruna', 'Billlie', 'https://i.imgur.com/lqqEOwe.mp4', 'A', 'Haruna', 'Series 3', 'true', 'false', 'https://i.imgur.com/DZuklDI.png', NULL, NULL),
    (289, 'Tsuki', 'Billlie', 'https://i.imgur.com/FYGNXUc.mp4', 'B', 'Tsuki', 'Series 3', 'true', 'false', 'https://i.imgur.com/LoKREUo.png', NULL, NULL),
    (290, 'Suhyeon', 'Billlie', 'https://i.imgur.com/3BzU58b.mp4', 'C', 'Suhyeon', 'Series 3', 'true', 'false', 'https://i.imgur.com/MkdBqRs.png', NULL, NULL),
    (291, 'Siyoon', 'Billlie', 'https://i.imgur.com/zVZnKCo.mp4', 'D', 'Siyoon', 'Series 3', 'true', 'false', 'https://i.imgur.com/SmKZMJi.png', NULL, NULL),
    (292, 'Moon Sua', 'Billlie', 'https://i.imgur.com/Rhf9cd1.mp4', 'D', 'Moon Sua', 'Series 3', 'true', 'false', 'https://i.imgur.com/OCm2vsj.png', NULL, NULL),
    (293, 'Bora', 'Cherry Bullet', 'https://i.imgur.com/eBoJhY5.mp4', 'S', 'Bora', 'Series 3', 'true', 'false', 'https://i.imgur.com/lWVlr5y.png', NULL, NULL),
    (294, 'Haeyoon', 'Cherry Bullet', 'https://i.imgur.com/lc7uKL8.mp4', 'B', 'Haeyoon', 'Series 3', 'true', 'false', 'https://i.imgur.com/lwpOdbf.png', NULL, NULL),
    (295, 'Yuju', 'Cherry Bullet', 'https://i.imgur.com/7EkiITM.mp4', 'C', 'Yuju', 'Series 3', 'true', 'false', 'https://i.imgur.com/4X7FGEE.png', NULL, NULL),
    (296, 'Jiwon', 'Cherry Bullet', 'https://i.imgur.com/sqYJxh9.mp4', 'C', 'Jiwon', 'Series 3', 'true', 'false', 'https://i.imgur.com/WdCrvlU.png', NULL, NULL),
    (297, 'Remi', 'Cherry Bullet', 'https://i.imgur.com/Tae0931.mp4', 'D', 'Remi', 'Series 3', 'true', 'false', 'https://i.imgur.com/W96cNn4.png', NULL, NULL),
    (298, 'Chaerin', 'Cherry Bullet', 'https://i.imgur.com/tsWy863.mp4', 'D', 'Chaerin', 'Series 3', 'true', 'false', 'https://i.imgur.com/UTMvZj6.png', NULL, NULL),
    (299, 'May', 'Cherry Bullet', 'https://i.imgur.com/4csWarm.mp4', 'D', 'May', 'Series 3', 'true', 'false', 'https://i.imgur.com/uBZbPH6.png', NULL, NULL),
    (300, 'Jeewon', 'cignature', 'https://i.imgur.com/A97We0N.mp4', 'SS', 'Jeewon', 'Series 3', 'true', 'false', 'https://i.imgur.com/J957LeY.png', NULL, NULL),
    (301, 'Semi', 'cignature', 'https://i.imgur.com/PlF80dZ.mp4', 'A', 'Semi', 'Series 3', 'true', 'false', 'https://i.imgur.com/Xg5aWCO.png', NULL, NULL),
    (302, 'Chaesol', 'cignature', 'https://i.imgur.com/Ceeev6d.mp4', 'B', 'Chaesol', 'Series 3', 'true', 'false', 'https://i.imgur.com/S9chAkK.png', NULL, NULL),
    (303, 'Seline', 'cignature', 'https://i.imgur.com/HJ8MK6i.mp4', 'C', 'Seline', 'Series 3', 'true', 'false', 'https://i.imgur.com/T8aPKlr.png', NULL, NULL),
    (304, 'Chloe', 'cignature', 'https://i.imgur.com/sMauahc.mp4', 'C', 'Chloe', 'Series 3', 'true', 'false', 'https://i.imgur.com/2QNF2QX.png', NULL, NULL),
    (305, 'Belle', 'cignature', 'https://i.imgur.com/KzbwZ77.mp4', 'D', 'Belle', 'Series 3', 'true', 'false', 'https://i.imgur.com/73DTdVb.png', NULL, NULL),
    (306, 'Dohee', 'cignature', 'https://i.imgur.com/OYiJNkt.mp4', 'D', 'Dohee', 'Series 3', 'true', 'false', 'https://i.imgur.com/uYklvDL.png', NULL, NULL),
    (307, 'Yujin', 'eite', 'https://i.imgur.com/luhfVZB.mp4', 'SS', 'Yujin', 'Series 3', 'true', 'false', 'https://i.imgur.com/gsWQqVH.png', NULL, NULL),
    (308, 'Yuisa', 'eite', 'https://i.imgur.com/F2gldDD.mp4', 'S', 'Yuisa', 'Series 3', 'true', 'false', 'https://i.imgur.com/1LJ1YV7.png', NULL, NULL),
    (309, 'Reo', 'eite', 'https://i.imgur.com/k6sBvT5.mp4', 'B', 'Reo', 'Series 3', 'true', 'false', 'https://i.imgur.com/KOh4TDN.png', NULL, NULL),
    (310, 'Ari', 'eite', 'https://i.imgur.com/ikLgx1M.mp4', 'C', 'Ari', 'Series 3', 'true', 'false', 'https://i.imgur.com/hx1aZ9h.png', NULL, NULL),
    (311, 'Sia', 'eite', 'https://i.imgur.com/qI30ixY.mp4', 'C', 'Sia', 'Series 3', 'true', 'false', 'https://i.imgur.com/Y1IbVIn.png', NULL, NULL),
    (312, 'Chaehyun', 'eite', 'https://i.imgur.com/qQ9EHqA.mp4', 'D', 'Chaehyun', 'Series 3', 'true', 'false', 'https://i.imgur.com/rucWir0.png', NULL, NULL),
    (313, 'Rena', 'eite', 'https://i.imgur.com/VbkzVaS.mp4', 'D', 'Rena', 'Series 3', 'true', 'false', 'https://i.imgur.com/p8045AJ.png', NULL, NULL),
    (314, 'Bomi', 'Girl Crush', 'https://i.imgur.com/TsJxYTW.mp4', 'SS', 'Bomi', 'Series 3', 'true', 'false', 'https://i.imgur.com/EdCn4F5.png', NULL, NULL),
    (315, 'Taeri', 'Girl Crush', 'https://i.imgur.com/N7oBU4D.mp4', 'A', 'Taeri', 'Series 3', 'true', 'false', 'https://i.imgur.com/5pFht8z.png', NULL, NULL),
    (316, 'Hayun', 'Girl Crush', 'https://i.imgur.com/CIZgFGP.mp4', 'B', 'Hayun', 'Series 3', 'true', 'false', 'https://i.imgur.com/7SvAnsW.png', NULL, NULL),
    (317, 'Zia', 'Girl Crush', 'https://i.imgur.com/8KGuAx0.mp4', 'C', 'Zia', 'Series 3', 'true', 'false', 'https://i.imgur.com/xmwZ6Wn.png', NULL, NULL),
    (318, 'Nancy', 'MOMOLAND', 'https://i.imgur.com/wYeQwtn.mp4', 'SS', 'Nancy', 'Series 3', 'true', 'false', 'https://i.imgur.com/D8Ct8kP.png', NULL, NULL),
    (319, 'Ahin', 'MOMOLAND', 'https://i.imgur.com/yH7LLAD.mp4', 'A', 'Ahin', 'Series 3', 'true', 'false', 'https://i.imgur.com/8jAcnNx.png', NULL, NULL),
    (320, 'Jane', 'MOMOLAND', 'https://i.imgur.com/IDbZn8g.mp4', 'B', 'Jane', 'Series 3', 'true', 'false', 'https://i.imgur.com/iFEQR69.png', NULL, NULL),
    (321, 'Hyebin', 'MOMOLAND', 'https://i.imgur.com/HP1Khbl.mp4', 'C', 'Hyebin', 'Series 3', 'true', 'false', 'https://i.imgur.com/Ztjpe7w.png', NULL, NULL),
    (322, 'JooE', 'MOMOLAND', 'https://i.imgur.com/UonDtBt.mp4', 'D', 'JooE', 'Series 3', 'true', 'false', 'https://i.imgur.com/Y4LGrat.png', NULL, NULL),
    (323, 'Nayun', 'MOMOLAND', 'https://i.imgur.com/O5wxOWW.mp4', 'D', 'Nayun', 'Series 3', 'true', 'false', 'https://i.imgur.com/pVR8hpL.png', NULL, NULL),
    (324, 'Magenta', 'QWER', 'https://i.imgur.com/Cz6NQ0R.mp4', 'SSS', 'Magenta', 'Series 3', 'true', 'false', 'https://i.imgur.com/oghVTHI.gif', NULL, NULL),
    (325, 'Chodan', 'QWER', 'https://i.imgur.com/GBcUYeW.mp4', 'S', 'Chodan', 'Series 3', 'true', 'false', 'https://i.imgur.com/y4F3ywN.png', NULL, NULL),
    (326, 'Siyeon', 'QWER', 'https://i.imgur.com/RZ80wxE.mp4', 'B', 'Siyeon', 'Series 3', 'true', 'false', 'https://i.imgur.com/KX9x40K.png', NULL, NULL),
    (327, 'Hina', 'QWER', 'https://i.imgur.com/AxnyIhi.mp4', 'B', 'Hina', 'Series 3', 'true', 'false', 'https://i.imgur.com/bXnq5OG.png', NULL, NULL),
    (328, 'Dita', 'Secret Number', 'https://i.imgur.com/q1XJgi3.mp4', 'SS', 'Dita', 'Series 3', 'true', 'false', 'https://i.imgur.com/E5neB2l.png', NULL, NULL),
    (329, 'Soodam', 'Secret Number', 'https://i.imgur.com/1I556VD.mp4', 'A', 'Soodam', 'Series 3', 'true', 'false', 'https://i.imgur.com/VISRU19.png', NULL, NULL),
    (330, 'Minji', 'Secret Number', 'https://i.imgur.com/9qpnWV0.mp4', 'B', 'Minji', 'Series 3', 'true', 'false', 'https://i.imgur.com/edwz4ba.png', NULL, NULL),
    (331, 'Zuu', 'Secret Number', 'https://i.imgur.com/bsljBus.mp4', 'C', 'Zuu', 'Series 3', 'true', 'false', 'https://i.imgur.com/3DIix57.png', NULL, NULL),
    (332, 'Léa', 'Secret Number', 'https://i.imgur.com/sSEn4Bx.mp4', 'D', 'Léa', 'Series 3', 'true', 'false', 'https://i.imgur.com/F4HGKPa.png', NULL, NULL),
    (333, 'Jinny', 'Secret Number', 'https://i.imgur.com/R8qQeWR.mp4', 'D', 'Jinny', 'Series 3', 'true', 'false', 'https://i.imgur.com/JIQVpFK.png', NULL, NULL),
    (334, 'Hyorin', 'SISTAR', 'https://i.imgur.com/bBE7DK9.mp4', 'SS', 'Hyorin', 'Series 3', 'true', 'false', 'https://i.imgur.com/cfO4cxL.png', NULL, NULL),
    (335, 'Soyu', 'SISTAR', 'https://i.imgur.com/h3w41Md.mp4', 'A', 'Soyu', 'Series 3', 'true', 'false', 'https://i.imgur.com/PQRRlat.png', NULL, NULL),
    (336, 'Bora', 'SISTAR', 'https://i.imgur.com/MyLvfUr.mp4', 'A', 'Bora', 'Series 3', 'true', 'false', 'https://i.imgur.com/5VMzgo1.png', NULL, NULL),
    (337, 'Dasom', 'SISTAR', 'https://i.imgur.com/TN4bBqY.mp4', 'B', 'Dasom', 'Series 3', 'true', 'false', 'https://i.imgur.com/sgwq7xU.png', NULL, NULL),
    (338, 'PSY', 'Soloist', 'https://i.imgur.com/yago1ul.mp4', 'GOD', 'PSY', 'Series 3', 'true', 'false', 'https://i.imgur.com/w5Xq0oq.gif', NULL, NULL),
    (339, 'Garam', 'Soloist', 'https://i.imgur.com/HFoVIZs.mp4', 'S', 'Garam', 'Series 3', 'true', 'false', 'https://i.imgur.com/JK912JH.png', NULL, NULL),
    (340, 'Yuju', 'Soloist', 'https://i.imgur.com/vXJH4Vm.mp4', 'A', 'Yuju', 'Series 3', 'true', 'false', 'https://i.imgur.com/BxSZl0E.png', NULL, NULL),
    (341, 'Gyuri', 'Soloist', 'https://i.imgur.com/wCHiwhq.mp4', 'C', 'Gyuri', 'Series 3', 'true', 'false', 'https://i.imgur.com/2KNgJEc.png', NULL, NULL),
    (342, 'Ailee', 'Soloist', 'https://i.imgur.com/R1EVXYe.mp4', 'C', 'Ailee', 'Series 3', 'true', 'false', 'https://i.imgur.com/inoL5Jj.png', NULL, NULL),
    (343, 'Kelly', 'TRI.BE', 'https://i.imgur.com/ZzkCd3h.mp4', 'A', 'Kelly', 'Series 3', 'true', 'false', 'https://i.imgur.com/ZqjtMYM.png', NULL, NULL),
    (344, 'Songsun', 'TRI.BE', 'https://i.imgur.com/pxzesuO.mp4', 'B', 'Songsun', 'Series 3', 'true', 'false', 'https://i.imgur.com/9ljjLT0.png', NULL, NULL),
    (345, 'Hyunbin', 'TRI.BE', 'https://i.imgur.com/CB0zMyl.mp4', 'C', 'Hyunbin', 'Series 3', 'true', 'false', 'https://i.imgur.com/s1sOWvA.png', NULL, NULL),
    (346, 'Jia', 'TRI.BE', 'https://i.imgur.com/3oR2FNA.mp4', 'C', 'Jia', 'Series 3', 'true', 'false', 'https://i.imgur.com/V6pBRTM.png', NULL, NULL),
    (347, 'Soeun', 'TRI.BE', 'https://i.imgur.com/BeLWpgM.mp4', 'D', 'Soeun', 'Series 3', 'true', 'false', 'https://i.imgur.com/dInDKWn.png', NULL, NULL),
    (348, 'Nana', 'woo!ah!', 'https://i.imgur.com/8R27Mlp.mp4', 'SSS', 'Nana', 'Series 3', 'true', 'false', 'https://i.imgur.com/r53qy1y.gif', NULL, NULL),
    (349, 'Lucy', 'woo!ah!', 'https://i.imgur.com/09kRn1m.mp4', 'A', 'Lucy', 'Series 3', 'true', 'false', 'https://i.imgur.com/VIxNmn9.png', NULL, NULL),
    (350, 'Minseo', 'woo!ah!', 'https://i.imgur.com/NnA4Za1.mp4', 'B', 'Minseo', 'Series 3', 'true', 'false', 'https://i.imgur.com/t41f3n7.png', NULL, NULL),
    (351, 'Sora', 'woo!ah!', 'https://i.imgur.com/yDHsFsy.mp4', 'C', 'Sora', 'Series 3', 'true', 'false', 'https://i.imgur.com/gQZuvg3.png', NULL, NULL),
    (352, 'Wooyeon', 'woo!ah!', 'https://i.imgur.com/7WJLooI.mp4', 'D', 'Wooyeon', 'Series 3', 'true', 'false', 'https://i.imgur.com/8GwsAxh.png', NULL, NULL),
    (353, 'Aria', 'X:IN', 'https://i.imgur.com/uMiiTER.mp4', 'SSS', 'Aria', 'Series 3', 'true', 'false', 'https://i.imgur.com/yJSjIDi.gif', NULL, NULL),
    (354, 'Nova', 'X:IN', 'https://i.imgur.com/Mv9eVu2.mp4', 'S', 'Nova', 'Series 3', 'true', 'false', 'https://i.imgur.com/XiC1Sa6.png', NULL, NULL),
    (355, 'E.Sha', 'X:IN', 'https://i.imgur.com/5h8QCCi.mp4', 'A', 'E.Sha', 'Series 3', 'true', 'false', 'https://i.imgur.com/cVRW4S1.png', NULL, NULL),
    (356, 'Nizz', 'X:IN', 'https://i.imgur.com/vGbNo8s.mp4', 'B', 'Nizz', 'Series 3', 'true', 'false', 'https://i.imgur.com/TVWxXVJ.png', NULL, NULL),
    (357, 'Hannah', 'X:IN', 'https://i.imgur.com/hfzodOv.mp4', 'D', 'Hannah', 'Series 3', 'true', 'false', 'https://i.imgur.com/Rm4swnv.png', NULL, NULL),
    (358, 'Juria', 'XG', 'https://i.imgur.com/nVOLUMY.mp4', 'SS', 'Juria', 'Series 3', 'true', 'false', 'https://i.imgur.com/xPQYYTJ.png', NULL, NULL),
    (359, 'Chisa', 'XG', 'https://i.imgur.com/EK9clKi.mp4', 'S', 'Chisa', 'Series 3', 'true', 'false', 'https://i.imgur.com/v1ywgtY.png', NULL, NULL),
    (360, 'Jurin', 'XG', 'https://i.imgur.com/HzymsPK.mp4', 'S', 'Jurin', 'Series 3', 'true', 'false', 'https://i.imgur.com/CK6XhJo.png', NULL, NULL),
    (361, 'Harvey', 'XG', 'https://i.imgur.com/6YaK6eq.mp4', 'B', 'Harvey', 'Series 3', 'true', 'false', 'https://i.imgur.com/9hH5aMm.png', NULL, NULL),
    (362, 'Hinata', 'XG', 'https://i.imgur.com/5Yoxwoo.mp4', 'C', 'Hinata', 'Series 3', 'true', 'false', 'https://i.imgur.com/QtcXbkn.png', NULL, NULL),
    (363, 'Cocona', 'XG', 'https://i.imgur.com/fdoajGj.mp4', 'D', 'Cocona', 'Series 3', 'true', 'false', 'https://i.imgur.com/KliUt3w.png', NULL, NULL),
    (364, 'Maya', 'XG', 'https://i.imgur.com/mXH8At9.mp4', 'D', 'Maya', 'Series 3', 'true', 'false', 'https://i.imgur.com/lGS7cJx.png', NULL, NULL);